// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/user_client_service.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Vendor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *Vendor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vendor) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Vendor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vendor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVendorRequest) Reset() {
	*x = CreateVendorRequest{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVendorRequest) ProtoMessage() {}

func (x *CreateVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVendorRequest.ProtoReflect.Descriptor instead.
func (*CreateVendorRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVendorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateVendorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVendorRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      int64                  `protobuf:"varint,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorRequest) Reset() {
	*x = GetVendorRequest{}
	mi := &file_v1_client_user_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorRequest) ProtoMessage() {}

func (x *GetVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_user_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorRequest.ProtoReflect.Descriptor instead.
func (*GetVendorRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_user_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetVendorRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

var File_v1_client_user_client_service_proto protoreflect.FileDescriptor

const file_v1_client_user_client_service_proto_rawDesc = "" +
	"\n" +
	"#v1/client/user_client_service.proto\x127github.com.martketplace.vkr.user.pkg.api.grpc.v1.client\"h\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"g\n" +
	"\x06Vendor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"h\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"d\n" +
	"\x13CreateVendorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x10GetVendorRequest\x12\x1b\n" +
	"\tvendor_id\x18\x01 \x01(\x03R\bvendorId2\xfb\x04\n" +
	"\x11UserClientService\x12\x91\x01\n" +
	"\aGetUser\x12G.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetUserRequest\x1a=.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.User\x12\x97\x01\n" +
	"\n" +
	"UpdateUser\x12J.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UpdateUserRequest\x1a=.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.User\x12\x9d\x01\n" +
	"\fCreateVendor\x12L.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.CreateVendorRequest\x1a?.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.Vendor\x12\x97\x01\n" +
	"\tGetVendor\x12I.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetVendorRequest\x1a?.github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.VendorB@Z>github.com/martketplace-vkr/user/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_user_client_service_proto_rawDescOnce sync.Once
	file_v1_client_user_client_service_proto_rawDescData []byte
)

func file_v1_client_user_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_user_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_user_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_user_client_service_proto_rawDesc), len(file_v1_client_user_client_service_proto_rawDesc)))
	})
	return file_v1_client_user_client_service_proto_rawDescData
}

var file_v1_client_user_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_client_user_client_service_proto_goTypes = []any{
	(*User)(nil),                // 0: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.User
	(*Vendor)(nil),              // 1: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.Vendor
	(*GetUserRequest)(nil),      // 2: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetUserRequest
	(*UpdateUserRequest)(nil),   // 3: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UpdateUserRequest
	(*CreateVendorRequest)(nil), // 4: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.CreateVendorRequest
	(*GetVendorRequest)(nil),    // 5: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetVendorRequest
}
var file_v1_client_user_client_service_proto_depIdxs = []int32{
	2, // 0: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.GetUser:input_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetUserRequest
	3, // 1: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.UpdateUser:input_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UpdateUserRequest
	4, // 2: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.CreateVendor:input_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.CreateVendorRequest
	5, // 3: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.GetVendor:input_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.GetVendorRequest
	0, // 4: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.GetUser:output_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.User
	0, // 5: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.UpdateUser:output_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.User
	1, // 6: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.CreateVendor:output_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.Vendor
	1, // 7: github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.UserClientService.GetVendor:output_type -> github.com.martketplace.vkr.user.pkg.api.grpc.v1.client.Vendor
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_client_user_client_service_proto_init() }
func file_v1_client_user_client_service_proto_init() {
	if File_v1_client_user_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_user_client_service_proto_rawDesc), len(file_v1_client_user_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_user_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_user_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_user_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_user_client_service_proto = out.File
	file_v1_client_user_client_service_proto_goTypes = nil
	file_v1_client_user_client_service_proto_depIdxs = nil
}
