syntax = "proto3";

package github.com.martketplace.vkr.user.pkg.api.grpc.v1.client;


option go_package = "github.com/martketplace-vkr/user/pkg/api/grpc/v1/client;client";



service UserClientService {
  rpc GetUser(GetUserRequest) returns (User);
  rpc UpdateUser(UpdateUserRequest) returns (User);
  rpc GetUserAddresses(GetUserAddressesRequest) returns (GetUserAddressesResponse);
  rpc AddUserAddress(AddUserAddressRequest) returns (AddUserAddressResponse);
}

message User {
  int64 id = 1;
  string email = 2;
  optional string first_name = 3;
  optional string last_name = 4;
  optional string avatar_url = 5;
}

message Address {
  int64 id = 1;
  string country =2;
  string city = 3;
  string  street = 4;
  string postal_code = 5;
  int64 user_id = 6;
}

message GetUserRequest {
  int64 user_id = 1;
  string email = 2;
}

message UpdateUserRequest {
  int64 user_id = 1;
  optional string first_name = 2;
  optional string last_name = 3;
  optional string avatar_url = 4;
  string email = 5;
}

message GetUserAddressesRequest {
  int64 UserID = 1;
}

message GetUserAddressesResponse{
  repeated Address addresses = 1;
} 

message AddUserAddressRequest {
  Address address = 1;
}

message AddUserAddressResponse{
  Address address = 1;
}